---
hosts:
  puppetmaster_domain: puppet,puppetmaster
  dbserver_domain: qaa2mysql,dbserver
  publisher_domain: pub.am.wso2.com,apim_loadbalancer2
  store_domain: store.am.wso2.com,apim_loadbalancer2
  keymanager_domain: keymanager.am.wso2.com,apim_loadbalancer2
  gateway_domain: gateway.am.wso2.com,apim_loadbalancer1
  gatewaymgt_domain: mgt.gateway.am.wso2.com,apim_loadbalancer1

nodes:
  apim_loadbalancer1: 192.168.57.149
  apim_gatewaymgr1: 192.168.57.131
  apim_gatewaywkr1: 192.168.57.130
  apim_loadbalancer2: 192.168.57.127
  apim_keymanager1: 192.168.57.145
  apim_keymanager2: 192.168.57.147
  apim_publisher1: 192.168.57.141
  apim_store1: 192.168.57.137 
  apim_store2: 192.168.57.136
  puppetmaster: 192.168.57.14
  dbserver: 192.168.57.140
  #nginx plus testing
  apim_loadbalancer3: 192.168.57.168
