---
hosts:
  puppetmaster_domain: puppet,puppetmaster
  dbserver_domain: qaamysql,dbserver
  publisher_domain: pub.am.wso2.com,apim_loadbalancer2
  store_domain: store.am.wso2.com,apim_loadbalancer1
  keymanager_domain: keymanager.am.wso2.com,apim_loadbalancer2
  gateway_domain: gateway.am.wso2.com,apim_loadbalancer1
  gatewaymgt_domain: mgt.gateway.am.wso2.com,apim_loadbalancer1

nodes:
  apim_loadbalancer1: 192.168.57.250
  apim_gateway1: 192.168.57.232
  apim_gateway2: 192.168.57.231
  apim_store1: 192.168.57.247
  apim_store2: 192.168.57.248
  apim_loadbalancer2: 192.168.57.239
  apim_keymanager1: 192.168.57.227
  apim_keymanager2: 192.168.57.225 
  apim_publisher1: 192.168.57.228
  puppetmaster: 192.168.57.148
  dbserver: 192.168.57.233
