---
hosts:
  dbserver_domain: qaa2mysql,dbserver
  puppetmaster_domain: puppet,puppetmaster
  publisher_domain: pub.am.wso2.com,apim_loadbalancer1
  store_domain: store.am.wso2.com,apim_loadbalancer1
  keymanager_domain: keymanager.am.wso2.com,apim_loadbalancer1
  gateway_domain: gateway.am.wso2.com,apim_loadbalancer1
  gatewaymgt_domain: mgt.gateway.am.wso2.com,apim_loadbalancer1

nodes:
  apim_loadbalancer1: 192.168.57.149
  apim_gatewaymgr1: 192.168.57.131
  apim_gatewaywkr1: 192.168.57.130
  apim_gatewaywkr2: 192.168.57.127
  apim_keymanager1: 192.168.57.145
  apim_keymanager2: 192.168.57.147
  apim_publisher1: 192.168.57.141
  apim_publisher2: 192.168.57.168
  apim_store1: 192.168.57.137
  apim_store2: 192.168.57.136
  dbserver: 192.168.57.140
  puppetmaster: 192.168.57.14
